### ISSUE TITLE
Lens not working on iPad

### ISSUE THREAD

**Issue by sianroderick** [elifesciences/lens-browser#32]
Clicking the Lens link from an article (e.g. http://elifesciences.org/content/4/e06253) on an iPad returns you to the article on the HW site, not the Lens version of the article.

**Comment by gnott** [comment]
The Lens team suggested the HW site version of the article has better mobile support than the current version of lens. A redirect was added for various mobile and smaller viewport devices.

This could be relaxed, removed, or some confirmation challenge of the redirect could be presented to the user. More discussion is welcome.

**Comment by sianroderick** [comment]
Thanks for the explanation.  I spoke to Ian too.  Sounds like it might be down to us to remove the Lens links for small screens to avoid confusion.  I'll close this issue for now.
